### ISSUE TITLE
Permalinks for changelog?

### ISSUE THREAD

**Issue by aried3r** [gettalong/hexapdf-website#3]
Hey! I was wondering if it's possible to have permalinks to the changelog of hexapdf. Currently, the link to the latest version is always https://hexapdf.gettalong.org/documentation/changelog.html#section. That is currently 0.22.0 (which is not in this repo yet btw), once e.g. 0.22.1 is released that link will point to `#section` again, while `0.22.0` will be `#section-1`.

It would be great to be able to link to specific releases. Not a big issues, since there's the CHANGELOG.md in the repo: https://github.com/gettalong/hexapdf/blob/master/CHANGELOG.md#0220---2022-03-26, but even that's not really permanent like GitHub Releases would be for example.

WDYT?

**Comment by gettalong** [comment]
Thanks for the suggestion! I already thought about doing this after linking to the last release with a "section" anchor.

I will probably generate anchors of the form `v0-22-0`.

**Comment by gettalong** [comment]
This is now checked-in to Github and will be live after the next HexaPDF release.
