### ISSUE TITLE
Example for forms doesn't work

### ISSUE THREAD

**Issue by bdewater** [gettalong/hexapdf-website#4]
Hi! I'm evaluating HexaPDF for work and started adapting this example here: https://github.com/gettalong/hexapdf-website/blob/f5bc2dbee03e5e09a27edc10bf6c9955f9de9d90/src/index.page#L120-L125

which did not work for me, I got `A PDF dictionary object needs a hash value, not a String (ArgumentError)`. Eventually I found [`field_value=(str)`](https://hexapdf.gettalong.org/documentation/api/HexaPDF/Type/AcroForm/TextField.html#method-i-field_value-3D) in the docs and get my test working.

**Comment by gettalong** [comment]
:facepalm: Thanks for finding that! I have fixed it via https://github.com/gettalong/hexapdf-website/commit/1b3ed50f3ee32593fbad860e99b48f040598e723.

You will find a more complete example at https://hexapdf.gettalong.org/examples/acro_form.html. Most of the example PDFs are actually generated when generating the website, so those are ensured to work.
